### ISSUE TITLE
Not compiling on Yosemite OSX in the Xcode 6.3

### ISSUE THREAD

**Issue by robksawyer** [scottnla/cortexFFGL#1]
I'm pretty new to FFGL and was downloading this in order to learn a bit more. However, it threw a bunch of errors on compile. Are these simple fixes?

<a href='http://postimg.org/image/5pq45v0d7/' target='_blank'><img src='http://s1.postimg.org/5pq45v0d7/Screen_Shot_2015_04_14_at_9_40_57_PM.jpg' border='0' alt="Screen Shot 2015 04 14 at 9 40 57 PM" /></a>

**Comment by Dewb** [comment]
Yep, the FFGL headers need to be tweaked a bit for modern compilers. This should do the trick:
https://github.com/Dewb/grainmarch/commit/fa6cab83f889201ed080392e9e6600a48c06cab1

**Comment by robksawyer** [comment]
Wow, you rock! These are great examples for folks to get started with FFGL. Especially if they’re working with Xcode. Thanks for sharing. 

**UPDATE:** I was referring to your grainmarch plugins, that is.

**Comment by robksawyer** [comment]
Updated over at https://github.com/robksawyer/cortexFFGL/tree/master.

**Comment by scottnla** [comment]
Awesome; I'll take a look over the weekend and pull any changes that I
confirm work.

thanks!
